force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Date_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Applied__c</fullName>
    <label>Date Applied</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler extends TriggerHandler {
    public override void beforeInsert() {
        JobApplTriggerHelper jobApplTrigHelper = new JobApplTriggerHelper();
        jobApplTrigHelper.setPrimaryContact(Trigger.new);
    }
}public with sharing class JobApplicationTriggerHandler {

    @AuraEnabled(cacheable=true)
    public static void beforeInsert(List<Job_Application__c> newJobApplications){
        List<Job_Application__c> duplicates = JobApplicationHandler.dupeCheck(newJobApplications);

        String errorMessage = 'You already saved this job.';
        AuraHandledException auraEx = new AuraHandledException(errorMessage);
        auraEx.setMessage(errorMessage);

        for(Job_Application__c dupe : duplicates){
            dupe.addError('You already saved this job.');
            throw auraEx;
        }


    }

    public static void updateDateApplied(List<Job_Application__c> newJobApplications, Map<Id,Job_Application__c> oldJobAppMap){
        for(Job_Application__c job : newJobApplications){
            if(job.Status__c == 'Applied' && oldJobAppMap.get(job.Id).Status__c != 'Applied'){
                job.Date_Applied__c = Date.today();
            }
        }
    }
}