force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant_Id__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Date_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Applied__c</fullName>
    <label>Date Applied</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Hired</fullName>
            </value>
            <value>
                <fullName>Closed - Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationHandlerTest.cls
@IsTest
public with sharing class JobApplicationHandlerTest {


    @IsTest
    static void testDuplicateJobApplicationCheck(){

        List<SObject> recordsToInsert = new List<SObject>();

        Account newAccount = new Account(
            Name = 'Test Company'
        );
        // insert newAccount;
        recordsToInsert.add(newAccount);

        Contact newContact = new Contact(
            FirstName = 'Test',
            LastName = 'Candidate',
            Email = 'test.candidate@test.com'
        );
        // insert newContact;
        recordsToInsert.add(newContact);
        insert recordsToInsert;

        Job_Posting__c newJobPosting = new Job_Posting__c(
            Name = 'Test Job Posting',
            Posting_Id__c = '12345',
            Company__c = newAccount.Id,
            Salary__c = '.00 - ,000.00'
        );
        insert newJobPosting;
        
        

        List<Job_Application__c> newJobApplications = new List<Job_Application__c>();
        
        for(Integer i = 0; i < 2; i++) {
            Job_Application__c newJobApplication = new Job_Application__c(
                Name = 'Test Job Application' + i,
                Status__c = 'Saved',
                Job_Posting__c = newJobPosting.Id,
                Applicant_Id__c = newContact.Id,
                Date_Applied__c = System.today()
        );
        
            newJobApplications.add(newJobApplication);
            
       }

       insert newJobApplications;

        Test.startTest();
        List<Job_Application__c> duplicateRecords = JobApplicationHandler.dupeCheck(newJobApplications);
        Test.stopTest();

        System.assertEquals(2, duplicateRecords.size());
        // System.assertEquals(, duplicateRecords[0].Id);



        

    


        


        
    }

}