force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CleanOlderJobApplications.cls
public with sharing class CleanOlderJobApplications  implements Schedulable {
    public CleanOlderJobApplications() {

    }
    // Query to find job applicatioins created x days ago.
    // Select Id from Job_Application__c where status__c != 'Closed' AND status__c != 'Accepted' AND createddate = N_Days_Ago:2 order by createddate desc LIMIT 100

    public void execute(SchedulableContext sc) {
        updateOlderJobApplications();
    }

    public static void updateOlderJobApplications() {
        List<Job_Application__c> olderJobs = [SELECT Id, Status__c, (SELECT Id FROM Events WHERE Type = 'Meeting') FROM Job_Application__c WHERE status__c != 'Closed' AND status__c != 'Accepted' AND createddate = N_Days_Ago:2 LIMIT 2];
        for(Job_Application__c jobRec : olderJobs) {
            jobRec.Status__c = 'Closed';
        }

        upsert olderJobs;

        JobApplHelper.sendExecutionStatusEmail('Job Application Cleanup', 'Stale Job Applications Cleanup Status', '# of Job Applications cleaned : ' + olderJobs.size(), null);
    }
}