force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the contact type.  
Job Applicant - is primarily used to identify the candidates who applies for open jobs.
Hiring Manager - is primarily used to identify the company&apos;s hiring manager for a given job posting
Recruiter - is primarily used to identify the recruiter for a given job posting</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job Applicant</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Recruiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Applicant_Id__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applicant Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Date_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Applied__c</fullName>
    <label>Date Applied</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications (Primary Contact)</relationshipLabel>
    <relationshipName>Job_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Date_Posted__c.field-meta.xml
<CustomField>
    <fullName>Date_Posted__c</fullName>
    <label>Date Posted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Contract - 6 Months</fullName>
            </value>
            <value>
                <fullName>Contract - 12 Months</fullName>
            </value>
            <value>
                <fullName>Contract - Long Term</fullName>
            </value>
            <value>
                <fullName>Contract To Hire</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Reference_Id__c</fullName>
    <externalId>true</externalId>
    <label>Job Reference Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Hired</fullName>
            </value>
            <value>
                <fullName>Closed - Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplHelperTest.cls
@isTest
public with sharing class JobApplHelperTest {
    public JobApplHelperTest() {

    }

    @isTest
    public static void testSendApplSubmissionEmail() {

        Account accountRec = new Account(Name='Test Hiring Company', Type='Job Posts');
        insert accountRec;

        Contact contactRec = new Contact(FirstName = 'Test', LastName = 'Name', Email = 'snk.95330@gmail.com', Type__c = 'Job Applicant');
        insert contactRec;
        Contact recruiterContact = new Contact(FirstName = 'Hiring Recruiter', LastName = 'Testing', Email = 'abc@xyz.com', Type__c = 'Recruiter', AccountId = accountRec.Id);
        insert recruiterContact;

        Job_Posting__c jobPostingRec = new Job_Posting__c(Company__c = accountRec.Id, Department__c = 'IT', Description__c = 'Test Job',
                                                                Date_Posted__c = Date.today(), Employment_Type__c = 'Full Time', Name = 'Senior Salesforce Developer', 
                                                                Job_Reference_Id__c = '-3886322937462864', Link__c = 'www.linkedin.com', Location__c = 'San Francisco, CA',
                                                                Salary__c = '$180K', Status__c = 'Open');

        insert jobPostingRec;

        Job_Application__c jobApplicationRec = new Job_Application__c(Applicant_Id__c = contactRec.Id, Job_Posting__c = jobPostingRec.Id, Status__c = 'Applied', Date_Applied__c = Date.today(), Name = jobPostingRec.Id + ' - ' + contactRec.Email);
        insert jobApplicationRec;

        Map<String, String> inputVariables = new Map<String, String>();
        inputVariables.put('value', jobPostingRec.Id);

        List<Map<String, String>> listObj = new List<Map<String, String>>();
        listObj.add(inputVariables);
        
        String jsonString = JSON.serialize(listObj);
        

        Test.startTest();
        JobApplHelper.sendApplSubmissionEmail(jsonString);
        Test.stopTest();

        Job_Application__c appl = [SELECT Id, Primary_Contact__c FROM Job_Application__c WHERE Id = :jobApplicationRec.Id];

        System.assertEquals(recruiterContact.Id, appl.Primary_Contact__c, 'Primary Contact was not set correctly');
    }

    @isTest
    public static void testIsCandidateExistInSystem() {
        Contact contactRec = new Contact(FirstName = 'Test', LastName = 'User', Email = 'test@test.com');
        insert contactRec;
        Test.startTest();
        Id contactId = JobApplHelper.isCandidateExistInSystem(contactRec.Email);
        Test.stopTest();
        System.assertEquals(null, contactId, 'Expected Id of the contact to be returned');
    }
}