force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the contact type.  
Job Applicant - is primarily used to identify the candidates who applies for open jobs.
Hiring Manager - is primarily used to identify the company&apos;s hiring manager for a given job posting
Recruiter - is primarily used to identify the recruiter for a given job posting</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Job Applicant</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Recruiter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Date_Applied__c.field-meta.xml
<CustomField>
    <fullName>Date_Applied__c</fullName>
    <label>Date Applied</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications (Primary Contact)</relationshipLabel>
    <relationshipName>Job_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Hired</fullName>
            </value>
            <value>
                <fullName>Closed - Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplTriggerHelper.cls
public with sharing class JobApplTriggerHelper {
    public void setPrimaryContact(List<SObject> objectList) {
        Map<Id, Id> companyIdMapByJobPostingId = new Map<Id, Id>();
        List<Id> jobPostingIdList = new List<Id>();

        for(Job_Application__c jobPostingRec : (List<Job_Application__c>)objectList) {
            jobPostingIdList.add(jobPostingRec.Job_Posting__c);
        }

        for(Job_Posting__c jobPostRec : [SELECT Id, Company__c  FROM Job_Posting__c WHERE Id in :jobPostingIdList]) {
            companyIdMapByJobPostingId.put(jobPostRec.Id, jobPostRec.Company__c);
        }

        Map<Id, List<Contact>> contactsMapByCompanyId = new Map<Id, List<Contact>>();
        
        for(Account acctRec : [SELECT Id,  (SELECT Id, Name, Type__c FROM Contacts WHERE Type__c = 'Hiring Manager' OR Type__c = 'Recruiter') 
                                                                FROM Account WHERE Id in :companyIdMapByJobPostingId.values() AND Type = 'Job Posts']) {
                contactsMapByCompanyId.put(acctRec.id, acctRec.Contacts);
        }

        for(Job_Application__c jobApplRec : (List<Job_Application__c>)objectList) {
            List<Contact> contactList = (List<Contact>)contactsMapByCompanyId.get(companyIdMapByJobPostingId.get(jobApplRec.Job_Posting__c));
            if(contactList != null && contactList.size() > 0) {
                jobApplRec.Primary_Contact__c = contactList.get(0).Id;
            }
        }
    }

    @AuraEnabled(cacheable=true)
    public static void jobApplicationDupeCheck(List<Job_Application__c> newJobApplications){
        List<Job_Application__c> duplicates = JobApplicationHandler.dupeCheck(newJobApplications);

        String errorMessage = 'You already saved this job.';
        AuraHandledException auraEx = new AuraHandledException(errorMessage);
        auraEx.setMessage(errorMessage);

        for(Job_Application__c dupe : duplicates){
            dupe.addError('You already saved this job.');
            throw auraEx;
        }

    }

    public static void updateDateApplied(List<SObject> newJobApplications, Map<Id,Job_Application__c> oldJobAppMap){
        for(Job_Application__c job : (List<Job_Application__c>)newJobApplications){
            if(job.Status__c == 'Applied' && oldJobAppMap.get(job.Id).Status__c != 'Applied'){
                job.Date_Applied__c = Date.today();
            }
        }
    }
}